#pragma config(Sensor, S2,     HTIRS2A,        sensorI2CCustom)
#pragma config(Sensor, S3,     HTIRS2B,        sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !edd!*//

/*
 * $Id: hitechnic-irseeker-v2-test1.c 133 2013-03-10 15:15:38Z xander $,
 */

#include "..\..\..\..\..\..\..\..\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-irseeker-v2.h"

// global variables
int dirAC_A = 0;
int dirDC_A = 0;

int dcS1_A, acS1_A = 0;
int dcS2_A, acS2_A = 0;
int dcS3_A, acS3_A = 0;
int dcS4_A, acS4_A = 0;
int dcS5_A, acS5_A = 0;

int dirAC_B = 0;
int dirDC_B = 0;

int dcS1_B, acS1_B = 0;
int dcS2_B, acS2_B = 0;
int dcS3_B, acS3_B = 0;
int dcS4_B, acS4_B = 0;
int dcS5_B, acS5_B = 0;

task main{

}
// the default DSP mode is 1200 Hz.
tHTIRS2DSPMode _mode = DSP_1200;

while(true){
  // Read the current non modulated signal direction
  dirDC_A = HTIRS2readDCDir(HTIRS2A);
  dirDC_B = HTIRS2readDCDir(HTIRS2B);
zsdfg


  // read the current modulated signal direction
  dirAC_A = HTIRS2readACDir(HTIRS2A);
  dirAC_B = HTIRS2readACDir(HTIRS2B);



  if (dirDC_A < 0 || dirDC_B < 0)
    break; // I2C read error occurred

  if (dirAC_A < 0 || dirAC_B < 0)
    break; // I2C read error occurred

   // Read the individual signal strengths of the internal sensors
   // Do this for both unmodulated (DC) and modulated signals (AC)
   if (!HTIRS2readAllDCStrength(HTIRS2A, dcS1_A, dcS2_A, dcS3_A, dcS4_A, dcS5_A))
     break; // I2C read error occurred
   if (!HTIRS2readAllACStrength(HTIRS2A, acS1_A, acS2_A, acS3_A, acS4_A, acS5_A ))
        break; // I2C read error occurred
	 if (!HTIRS2readAllDCStrength(HTIRS2B, dcS1_B, dcS2_B, dcS3_B, dcS4_B, dcS5_B))
      break; // I2C read error occurred
   if (!HTIRS2readAllACStrength(HTIRS2B, acS1_B, acS2_B, acS3_B, acS4_B, acS5_B ))
      break; // I2C read error occurred

   HTIRS2readAllDCStrength(HTIRS2A, dcS1_A, dcS2_A, dcS3_A, dcS4_A, dcS5_A);
   HTIRS2readAllACStrength(HTIRS2A, acS1_A, acS2_A, acS3_A, acS4_A, acS5_A);
   HTIRS2readAllDCStrength(HTIRS2B, dcS1_B, dcS2_B, dcS3_B, dcS4_B, dcS5_B);
   HTIRS2readAllACStrength(HTIRS2B, acS1_B, acS2_B, acS3_B, acS4_B, acS5_B);

}
