#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightfront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftfront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightrear,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftrear,      tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

void forward(int pwr,int rotations){
	nMotorEncoder[rightfront] = 0;
	while(nMotorEncoder[rightfront] <= rotations)
		{
		motor[rightfront] = pwr;
		motor[leftfront] = pwr;
		motor[rightrear] = pwr;
		motor[leftrear] = pwr;
	}
}
task main(){
int pwr = 20;
int rotations = 1200;
//1 rotation = 1200
forward(pwr,rotations);
}
