#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     FR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FL,            tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     BR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BL,            tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "GyroAutoDependency.c"

void forward(int pwr,int degrees){
while( setJoysticks(0,0,pwr/100,0) != degrees){}//add ratio!!
}
void backward(int pwr,int degrees){
while( setJoysticks(0,0,-1*pwr/100,0) != degrees){}//add ratio!!
}
void turnright(int pwr,int degrees){
while( setJoysticks(0,pwr/100,0,0) != degrees){}//add ratio!!
}
void turnleft(int pwr,int degrees){
while( setJoysticks(0,0,-1*pwr/100,0) != degrees){}//add ratio!!
}
