#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     RightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     LeftRear,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     elevator_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     intake_motor,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     LeftFront,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     RightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    grabber1_servo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    grabber2_servo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutonomousDirections.h"
#include "JoystickDriver.c"

task main()
{
//power,rotations
//2500 is around 1 rotation
//2500 rotations turn is 90 degreese()
getJoystickSettings(joystick);
servo[door] = 0;
nMotorEncoder[elevator_motor] = 0;
nMotorEncoder[RightFront] = 0;
nMotorEncoder[LeftFront] = 0;
nMotorEncoder[LeftRear] = 0;
nMotorEncoder[RightRear] = 0;
servo[grabber1_servo] = 123;
servo[grabber2_servo] = 123;
waitForStart();

backward(20,9400);
allstop();
wait10Msec(50);
servo[grabber1_servo] = 255;
servo[grabber2_servo] = 0;
wait10Msec(50);
while(nMotorEncoder[elevator_motor] > -3200){
motor[elevator_motor] = -100;
}
allstop();
wait10Msec(100);
servo[door] = 123;
wait10Msec(100);
nMotorEncoder[elevator_motor] = 0;
while(nMotorEncoder[elevator_motor] < 300){
motor[elevator_motor] = 100;
}
allstop();
turnleft(100,6200);
allstop();
wait10Msec(50);
backward(50,9500);
allstop();
wait10Msec(50);
moveleft(50,2000);
allstop();

}
