#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     RightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     LeftRear,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     elevator_motor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     intake_motor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     RightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    door,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutonomousDirections.h"
#include "JoystickDriver.c"

task main()
{
//ENCODERS NOT FUNCTIONING RIGHT NOW ENDLESSLY GOES
//power,rotations
//2500 is around 1 rotation
//2500 rotations turn is 90 degreese()
getJoystickSettings(joystick);
backward(100,1);
wait10Msec(50);
allstop();
wait10Msec(50);
servo[RightGoal] = 0;
servo[LeftGoal] = 255;
wait10Msec(50);
while(nMotorEncoder[elevator_motor] < 3200){
motor[elevator_motor] = 100;
}
allstop();
wait10Msec(100);
servo[door] = 123;
wait10Msec(100);
nMotorEncoder[elevator_motor] = 0;
while(nMotorEncoder[elevator_motor] > 0){
motor[elevator_motor] = -100;
}
allstop();
turnleft(100,6200);
allstop();
wait10Msec(50);
backward(50,9500);
wait10Msec(50);
allstop();
turnright(50,5000);
wait10Msec(50);
allstop();
backward(50,2500);
wait10Msec(50);
allstop();
servo[RightGoal] = 255;
servo[LeftGoal] = 0;
}
