#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C2_1,     RightRear,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    door,                 tServoStandard)
#pragma config(Motor,  mtr_S1_C3_1,     elevator_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     intake_motor,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutonomousDirections.h"
#include "JoystickDriver.c"

task main()
{
//power,rotations
//2500 is around 1 rotation
//2500 rotations turn is 90 degreese()
getJoystickSettings(joystick);
servo[door] = 0;
nMotorEncoder[elevator_motor] = 0;
nMotorEncoder[RightFront] = 0;
nMotorEncoder[LeftFront] = 0;
nMotorEncoder[LeftRear] = 0;
nMotorEncoder[RightRear] = 0;
servo[RightGoal] = 123;
servo[LeftGoal] = 123;
//waitForStart();
backward(25,9400);
allstop();
wait10Msec(50);
servo[RightGoal] = 255;
servo[LeftGoal] = 0;
wait10Msec(50);
while(nMotorEncoder[elevator_motor] > -3200){
motor[elevator_motor] = -100;
}
allstop();
wait10Msec(100);
servo[door] = 123;
wait10Msec(100);
nMotorEncoder[elevator_motor] = 0;
while(nMotorEncoder[elevator_motor] < 300){
motor[elevator_motor] = 100;
}
allstop();
turnleft(100,6200);
allstop();
wait10Msec(50);
backward(50,9500);
wait10Msec(50);
allstop();
turnright(50,5000);
wait10Msec(50);
allstop();
backward(50,2500);
wait10Msec(50);
allstop();
Ryswag
}
