#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C2_1,     RightRear,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    door,                 tServoStandard)
#pragma config(Motor,  mtr_S1_C3_1,     elevator_motor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     intake_motor,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobotx
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task elevator()
{
	while(true)
		{
		if(joystick.joy2_y2 > 15){
				motor[elevator_motor] = -100;
			}
		else if(joystick.joy2_y2 < -15){
				motor[elevator_motor] = 100;
			}
		else{
			motor[elevator_motor] = 0;
			}
		}
}

//Use Joystick 1 buttons to grab the rolling goal.
task grab()
{
	bool counter = true;
	while(true){
		if(joy2Btn(6) == 1){
		counter = true;
		}else if(joy2Btn(5) == 1){
		counter = false;
	  }
	  if(counter == true){
	  servo[grabber1_servo] = 0;
		servo[grabber2_servo] = 255;
	  }else{
	  servo[grabber1_servo] = 255;
			servo[grabber2_servo] = 0;
	  }
	}
}

//Use a two buttons to turn on/off the intake.  Intake will continuously run.
task intake()
{
	while(true){
		if(joy2Btn(7) == 1){
			motor[intake_motor] = -70;
		}else if(joy2Btn(8) == 1){
			 motor[intake_motor] = 70;
	  }
		else
			{
				motor[intake_motor] = 0;
			}

	}

}
task dropBall(){
while(true){
	if(joy2Btn(3) == 1){
		servo[door] = 123;
	}else{
		servo[door] = 0;
	}
}
}
task monitorB(){
	while(true){
	nxtDisplayTextLine(7,"%d",joy2Btn(3));
}
}
float x1,y1,x2,y2,LF,RF,LB,RB= 0;

task driver(){

	int minJoy = 5;
	while(true){
		// Resets movement values

		// Get joystick values
		x1 = joystick.joy1_x1*.7;y1 = -joystick.joy1_y1*.7;
		x2 = joystick.joy1_x2*.7;y2 = joystick.joy1_y2*.7;

		//LF = x1; RF = x1; LB = -x1; RB = -x1;
		 LF = y1;
		 RF = y2;
		 LB = y1;
		 RB = y2;

		if (abs(joystick.joy1_x1)<minJoy&&abs(joystick.joy1_y1)<minJoy&&abs(joystick.joy1_x2)<minJoy){
			LF = 0;RF = 0;LB = 0;RB = 0;
		}

		// Apply Finished values to motors.
		motor[LeftFront] = LF;
		motor[RightFront] = RF;
		motor[LeftRear] = LB;
		motor[RightRear] = RB;
		wait1Msec(10); // necessary if using task control to allow for other tasks to run
	}
}

task main()
{
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase
  bFloatDuringInactiveMotorPWM = false;
  StartTask(driver);
  StartTask(grab);
  StartTask(elevator);
  StartTask(intake);
  StartTask(dropBall);
  while(true){
  wait1Msec(10);

}
}
