#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     RightRear,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     hwShooter,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     Feeder,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    Dumper60,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    Dumper30,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobotx
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////



task manipulator(){
 while(true)
  {
    //getJoystickSettings(joystick);  // Update Buttons and Joysticks

    if(joy2Btn(1)==1){servo[LeftGoal] = 230; servo[RightGoal] = 0;}
    else{servo[LeftGoal] = 140;servo[RightGoal] = 90;}
    if(joy2Btn(2) == 1){servo[Dumper60] = 0;}
    else{servo[Dumper60]=100;}


    motor[hwShooter] = joystick.joy2_y1*100/128;
   	if(motor[hwShooter]>15){motor[Feeder]=-50;}
   	else{motor[Feeder]=0;}
  }


}
float x1,y1,x2,y2,LF,RF,LB,RB= 0;

task driver(){

	int minJoy = 5;
	while(true){
		// Resets movement values

		// Get joystick values
		x1 = joystick.joy1_x1*.5;y1 = -joystick.joy1_y1*.5;
		x2 = joystick.joy1_x2*.5;y2 = joystick.joy1_y2*.5;

		//LF = x1; RF = x1; LB = -x1; RB = -x1;
		 LF = y1;
		 RF = y2;
		 LB = y1;
		 RB = y2;

		if (abs(joystick.joy1_x1)<minJoy&&abs(joystick.joy1_y1)<minJoy&&abs(joystick.joy1_x2)<minJoy){
			LF = 0;RF = 0;LB = 0;RB = 0;
		}

		// Apply Finished values to motors.
		motor[LeftFront] = LF;
		motor[RightFront] = RF;
		motor[LeftRear] = LB;
		motor[RightRear] = RB;
		wait1Msec(10); // necessary if using task control to allow for other tasks to run
	}
}

task main()
{
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase
  bFloatDuringInactiveMotorPWM = false;
  StartTask(driver);
  StartTask(manipulator);
  while(true){
  wait1Msec(10);

}
}
