#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightRear,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
float max (float a,float b){
	if(a>=b){return a;}
	else if(a<b){return b;}
	else {return a;}
}

float norm4 (float in1, float in2, float in3, float in4){
float ain1=abs(in1);float ain2=abs(in2);float ain3=abs(in3);float ain4=abs(in4);
float comp1=max(ain1,ain2);
float comp2=max(comp1,ain3);
float comp3=max(comp2,ain4);
//float comp3 = max(max(max(abs(in1),abs(in2)),abs(in3)),abs(in4));
if(comp3>100){
in1/=comp3*100;
in2/=comp3*100;
in3/=comp3*100;
in4/=comp3*100;
}
float normal_out[4] = {in1,in2,in3,in4};
return normal_out;
}
task Buttons(){

 while(true)
  {
    getJoystickSettings(joystick);  // Update Buttons and Joysticks

    if(joy1Btn(1) == 1)                  // If Joy1-Button1 is pressed:
    {
      servo[LeftGoal] = 230;
      servo[RightGoal] = 0;
    }
    else                            // If Joy1-Button1 is NOT pressed:
    {
     servo[LeftGoal] = 0;
     servo[RightGoal] = 230;
    }
  }


}
float x1,y1,x2,y2,LF,RF,LB,RB= 0;
task drive(){

	int minJoy = 5;
	while(true){
		// Resets movement values
		LF = 0;RF = 0;LB = 0;RB = 0;
		// Get joystick values
		x1 = joystick.joy1_x1*.6;y1 = joystick.joy1_y1*.6;
		x2 = joystick.joy1_x2*.6;y2 = joystick.joy1_y2*.6;

		LF = x1-x2+y1; RF = y1+x2-x1; LB = y1-x2-x1; RB = y1+x2+x1;
	///	float normout[4]={0,0,0,0};
//		normout= norm4(LF,RF,LB,RB);
//		LF=normout[0];RF=normout[1];LB=normout[2];RB=normout[3];

		if (abs(joystick.joy1_x1)<minJoy&&abs(joystick.joy1_y1)<minJoy&&abs(joystick.joy1_x2)<minJoy){
			LF = 0;RF = 0;LB = 0;RB = 0;
		}
		// Apply Finished values to motors.
		motor[LeftFront] = LF;
		motor[RightFront] = RF;
		motor[LeftRear] = LB;
		motor[RightRear] = RB;
		wait1Msec(10); // necessary if using task control to allow for other tasks to run
	}
}

task main()
{
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase
  bFloatDuringInactiveMotorPWM = false;
  StartTask(drive);
  StartTask(Buttons);
  while(true){
  	wait1Msec(10);

}
}
