#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightRear,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutonomousDirections.h"
int btn = 0;
task Buttons(){

 while(true)
  { // Update Buttons and Joysticks

    if(btn == 1)                  // If Joy1-Button1 is pressed:
    {
      servo[LeftGoal] = 230;
      servo[RightGoal] = 0;
    }
    else                            // If Joy1-Button1 is NOT pressed:
    {
     servo[LeftGoal] = 0;
     servo[RightGoal] = 230;
    }
  }

}
task main()
{
	StartTask(Buttons);
//power,rotations
//1440 is around 1 rotation
//2500 rotations turn is 90 degrees
//backward(10,10000);



			//Initialize servos
	//	 	servo[LeftGoal] = 0;
  //   	servo[RightGoal] = 230;

     	//1. Drives off Ramp
			forward(50,10000);
wait1Msec(300);
			//2. Grab the goal
	//		servo[LeftGoal] = 230;
  //    servo[RightGoal] = 0;
btn = 1;

//3. Drop the ball
			//4. Move to parking zone
			moveleft(50,3500);
			wait1Msec(300);
			backward(30,10000);
			wait1Msec(300);
			turnleft(30,3000);
			wait1Msec(300);
			forward(30,1000);
			wait1Msec(300);
			allstop();



//forward(50,100000)




}
