#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightRear,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "SyncedAutonomousDirections.h"

task main()
{
//power,rotations
//1440 is around 1 rotation
//2500 rotations turn is 90 degrees


			//Initialize servos
		 	servo[LeftGoal] = 0;
     	servo[RightGoal] = 230;

     	//1. Drives off Ramp
			backward(50,14000);

			//2. Grab the goal
			servo[LeftGoal] = 230;
      servo[RightGoal] = 0;


//3. Drop the ball
			//4. Move to parking zone
			turnleft(,550);
			backward(50,7500);




forward(50,100000)







//3. Score in 30cm goal

//4. Knock over Center Poll



}
