#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightRear,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    Dumper,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutonomousDirections.h"

task main()
{
//power,rotations
//1440 is around 1 rotation
//2500 rotations turn is 90 degrees
//backward(10,10000);



			//Initialize servos
		 	servo[LeftGoal] = 140;
     	servo[RightGoal] = 90;
     	servo[Dumper]=100;

     	//1. Drives off Ramp
/*			forward(30,8000);
			allstop();
			wait1Msec(300);
			moveleft(50,3000);
			wait1Msec(300);
			allstop();*/
			forward(30,2000);
			wait1Msec(300);
			for (int i = 0; i <5; i++){
				turnleft(30,250);
				forward(30,250);
				turnright(30,250);
				forward(30,250);
			}
			forward(30,1000);
			wait1Msec(500);
			servo[LeftGoal] = 230;
      servo[RightGoal] = 0;
      servo[Dumper]=0;
			wait1Msec(1000);
			moveleft(50,3500);
			allstop();
			wait1Msec(300);
			backward(30,10000);
			allstop();
			wait1Msec(300);
			turnleft(30,3000);
			allstop();
			wait1Msec(300);
			forward(30,1000);
			allstop();



//forward(50,100000)




}
