#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2A,        sensorI2CCustom)
#pragma config(Sensor, S4,     HTIRS2B,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightRear,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// GOES FORWARD :)
void forward(int pwr,int rotations){
	nMotorEncoder[RightFront] = 0;
	bMotorReflected[RightFront] = false;
	bMotorReflected[LeftFront] = true;
	bMotorReflected[RightRear] = false;
	bMotorReflected[LeftRear] = true;
	while(nMotorEncoder[RightFront] <= rotations){
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor[RightRear] = pwr;
		motor[LeftRear] = pwr;
	}
}
// GOES BACKWARD (:
void backward(int pwr,int rotations){
	nMotorEncoder[RightFront] = 0;
	bMotorReflected[RightFront] = true;
	bMotorReflected[LeftFront] = false;
	bMotorReflected[RightRear] = true;
	bMotorReflected[LeftRear] = false;
	while(nMotorEncoder[RightFront] <= rotations){
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor[RightRear] = pwr;
		motor[LeftRear] = pwr;
	}
}
// TURNS RIGHT >.>
void turnright(int pwr,int rotations){
	nMotorEncoder[RightFront] = 0;
	bMotorReflected[RightFront] = true;
	bMotorReflected[LeftFront] = true;
	bMotorReflected[RightRear] = true;
	bMotorReflected[LeftRear] = true;
	while(nMotorEncoder[RightFront] <= rotations){
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor[RightRear] = pwr;
		motor[LeftRear] = pwr;
	}
}
//TURNS LEFT <.<
void turnleft(int pwr,int rotations){
	nMotorEncoder[LeftFront] = 0;
	bMotorReflected[RightFront] = false;
	bMotorReflected[LeftFront] = false;
	bMotorReflected[RightRear] = false;
	bMotorReflected[LeftRear] = false;
	while(nMotorEncoder[RightFront] <= rotations){
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor[RightRear] = pwr;
		motor[LeftRear] = pwr;
	}
}
//movesright

void moveright (int pwr, int rotations) {
	nMotorEncoder[LeftFront] = 0;
	bMotorReflected[RightFront] = true;
	bMotorReflected[LeftFront] = false;
	bMotorReflected[RightRear] = false;
	bMotorReflected[LeftRear] = true;
	while(nMotorEncoder[RightFront] <= rotations) {
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor [RightRear] = pwr;
		motor [LeftRear] = pwr;
	}
}

void moveleft (int pwr, int rotations) {
	nMotorEncoder[LeftFront] = 0;
	bMotorReflected[RightFront] = false;
	bMotorReflected[LeftFront] = true;
	bMotorReflected[RightRear] = true;
	bMotorReflected[LeftRear] = false;
	while(nMotorEncoder[RightFront] <= rotations) {
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor [RightRear] = pwr;
		motor [LeftRear] = pwr;
	}


}
void allstop (void) {
		motor[RightFront] = 0;
		motor[LeftFront] = 0;
		motor [RightRear] = 0;
		motor [LeftRear] = 0;
	}
