#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LeftRear,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightRear,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    LeftGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RightGoal,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// GOES FORWARD :)
void movemotors (int pwr, int rotations){
	nMotorEncoder[RightFront] = 0;
	nMotorEncoder[LeftFront] = 0;
	int radj=0;
	int ladj=0;
	while((nMotorEncoder[RightFront] <= rotations)){
		if(nMotorEncoder[RightFront] < nMotorEncoder[LeftFront]){
			radj+=1;ladj-=1;}
		else if(nMotorEncoder[RightFront] < nMotorEncoder[LeftFront]){
			radj-=1;ladj+=1;}
		motor[RightFront] = pwr+radj;
		motor[LeftFront] = pwr+ladj;
		motor[RightRear] = pwr;
		motor[LeftRear] = pwr;
	}
}
void forward(int pwr,int rotations){
	bMotorReflected[RightFront] = false;
	bMotorReflected[LeftFront] = true;
	bMotorReflected[RightRear] = false;
	bMotorReflected[LeftRear] = true;
	movemotors(pwr,rotations);

}
// GOES BACKWARD (:
void backward(int pwr,int rotations){
	nMotorEncoder[RightFront] = 0;
	bMotorReflected[RightFront] = true;
	bMotorReflected[LeftFront] = false;
	bMotorReflected[RightRear] = true;
	bMotorReflected[LeftRear] = false;
	while(nMotorEncoder[RightFront] <= rotations){
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor[RightRear] = pwr;
		motor[LeftRear] = pwr;
	}
}
// TURNS RIGHT >.>
void turnright(int pwr,int rotations){
	nMotorEncoder[RightFront] = 0;
	bMotorReflected[RightFront] = true;
	bMotorReflected[LeftFront] = true;
	bMotorReflected[RightRear] = true;
	bMotorReflected[LeftRear] = true;
	while(nMotorEncoder[RightFront] <= rotations){
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor[RightRear] = pwr;
		motor[LeftRear] = pwr;
	}
}
//TURNS LEFT <.<
void turnleft(int pwr,int rotations){
	nMotorEncoder[LeftFront] = 0;
	bMotorReflected[RightFront] = false;
	bMotorReflected[LeftFront] = false;
	bMotorReflected[RightRear] = false;
	bMotorReflected[LeftRear] = false;
	while(nMotorEncoder[RightFront] <= rotations){
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor[RightRear] = pwr;
		motor[LeftRear] = pwr;
	}
}
//movesright

void moveright (int pwr, int rotations) {
	nMotorEncoder[LeftFront] = 0;
	bMotorReflected[RightFront] = true;
	bMotorReflected[LeftFront] = false;
	bMotorReflected[RightRear] = false;
	bMotorReflected[LeftRear] = true;
	while(nMotorEncoder[RightFront] <= rotations) {
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor [RightRear] = pwr;
		motor [LeftRear] = pwr;
	}
}

void moveleft (int pwr, int rotations) {
	nMotorEncoder[LeftFront] = 0;
	bMotorReflected[RightFront] = false;
	bMotorReflected[LeftFront] = true;
	bMotorReflected[RightRear] = true;
	bMotorReflected[LeftRear] = false;
	while(nMotorEncoder[RightFront] <= rotations) {
		motor[RightFront] = pwr;
		motor[LeftFront] = pwr;
		motor [RightRear] = pwr;
		motor [LeftRear] = pwr;
	}


}
void allstop (void) {
		motor[RightFront] = 0;
		motor[LeftFront] = 0;
		motor [RightRear] = 0;
		motor [LeftRear] = 0;
	}
	//THIS MAY NOT WORK
void offramp (void) {
forward(100,2400);
turnright(100,1200);
}
